# -*- coding: utf-8 -*-
"""AI/ML Training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TPfLmrq5Wlcq6MvrxhMYHtaMzI5l1-dP
"""

pip install groq

from groq import Groq
Client=Groq(api_key="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")
def answerto(text):
    model="llama3-8b-8192"
    messages=[{"role":"user", "content":f"Answer the following question {text}"}]
    response=Client.chat.completions.create(model=model, messages=messages, temperature=0.5)
    return response.choices[0].message.content.strip().lower()

answer=answerto("What is the best place to visit in Islamabad?")
print(answer)